In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [2]:
from dotenv import load_dotenv
import os
load_dotenv()
# print(os.getenv('id'))
# print(os.getenv('key'))

True

In [50]:
import requests
import pandas as pd

# ✅ 인증 정보
CERT_KEY = os.getenv('key')
CERT_ID = os.getenv('id')

# ✅ API 요청 URL 및 파라미터 설정
url = 'https://www.kamis.or.kr/service/price/xml.do'
params = {
    'action': 'periodWholesaleProductList',  # 신) 일별 도매 가격 자료
    'p_cert_key': CERT_KEY,
    'p_cert_id': CERT_ID,
    'p_returntype': 'json',
    'p_product_cls_code': '02',       # 상품분류: 01=소매, 02=도매
    'p_item_category_code': '200',    # 대분류 코드 예: 200=과일류
    'p_item_code': '211',             # 품목코드 예: 211=사과
    'p_kind_code': '05',              # 품종코드 예: 05=홍로
    'p_county_code': '1101',          # 지역코드 예: 서울=1101
    'p_convert_kg_yn': 'N',
    'p_startday': '2024-06-01',
    'p_endday': '2024-06-30'
}

# ✅ API 호출
response = requests.get(url, params=params)

# ✅ 결과 확인 및 정리
if response.status_code == 200:
    #print(response.json())
    json_data = response.json()
    data = json_data.get('data')
    #print(json_data.keys())
   
    df = pd.DataFrame(data.get('item'))
    display(df.head())
else:
    print("API 호출 실패:", response.status_code)

  itemname kindname countyname marketname  yyyy regday   price
0     None     None         평균       None  2024  06/03  49,820
1     None     None         평균       None  2024  06/04  49,820
2     None     None         평균       None  2024  06/05  49,820
3     None     None         평균       None  2024  06/07  49,820
4     None     None         평균       None  2024  06/10  49,820

In [49]:
pd.DataFrame(data.get('item'))

    itemname    kindname countyname marketname  yyyy regday   price
0       None        None         평균       None  2024  06/03  49,820
1       None        None         평균       None  2024  06/04  49,820
2       None        None         평균       None  2024  06/05  49,820
3       None        None         평균       None  2024  06/07  49,820
4       None        None         평균       None  2024  06/10  49,820
..       ...         ...        ...        ...   ...    ...     ...
128        쌀  20kg(20kg)         대전         인동  2024  06/24  48,600
129        쌀  20kg(20kg)         대전         인동  2024  06/25  48,600
130        쌀  20kg(20kg)         대전         인동  2024  06/26  48,600
131        쌀  20kg(20kg)         대전         인동  2024  06/27  48,600
132        쌀  20kg(20kg)         대전         인동  2024  06/28  48,600

[133 rows x 7 columns]

In [46]:
for itemname, kindname, countyname, marketname, yyyy, regday data.get('item')

[{'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/03',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/04',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/05',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/07',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/10',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/11',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/12',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/13',
  'price': '49,820'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/14',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/17',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/18',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/19',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/20',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/21',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/24',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/25',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/26',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/27',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평균',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/28',
  'price': '49,740'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/03',
  'price': '48,531'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/04',
  'price': '48,582'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/05',
  'price': '48,600'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/07',
  'price': '48,625'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/10',
  'price': '48,687'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/11',
  'price': '48,687'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/12',
  'price': '48,687'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/13',
  'price': '48,673'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/14',
  'price': '48,660'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/17',
  'price': '48,651'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/18',
  'price': '48,639'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/19',
  'price': '48,627'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/20',
  'price': '48,580'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/21',
  'price': '48,543'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/24',
  'price': '48,468'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/25',
  'price': '48,479'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/26',
  'price': '48,489'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/27',
  'price': '48,500'},
 {'itemname': None,
  'kindname': None,
  'countyname': '평년',
  'marketname': None,
  'yyyy': '2024',
  'regday': '06/28',
  'price': '48,500'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/03',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/04',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/05',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/07',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/10',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/11',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/12',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/13',
  'price': '49,400'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/14',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/17',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/18',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/19',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/20',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/21',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/24',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/25',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/26',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/27',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '서울',
  'marketname': '양곡도매',
  'yyyy': '2024',
  'regday': '06/28',
  'price': '49,000'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/03',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/04',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/05',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/07',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/10',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/11',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/12',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/13',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/14',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/17',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/18',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/19',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/20',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/21',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/24',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/25',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/26',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/27',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '부산',
  'marketname': '부전',
  'yyyy': '2024',
  'regday': '06/28',
  'price': '51,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/03',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/04',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/05',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/07',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/10',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/11',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/12',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/13',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/14',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/17',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/18',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/19',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/20',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/21',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/24',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/25',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/26',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/27',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대구',
  'marketname': '서문',
  'yyyy': '2024',
  'regday': '06/28',
  'price': '50,200'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/03',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/04',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/05',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/07',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/10',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/11',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/12',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/13',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/14',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/17',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/18',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/19',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/20',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/21',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/24',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/25',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/26',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/27',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '광주',
  'marketname': '양동',
  'yyyy': '2024',
  'regday': '06/28',
  'price': '49,300'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/03',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/04',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/05',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/07',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/10',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/11',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/12',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/13',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/14',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/17',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/18',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/19',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/20',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/21',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/24',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/25',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/26',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/27',
  'price': '48,600'},
 {'itemname': '쌀',
  'kindname': '20kg(20kg)',
  'countyname': '대전',
  'marketname': '인동',
  'yyyy': '2024',
  'regday': '06/28',
  'price': '48,600'}]

In [34]:
# url = f'http://www.kamis.or.kr/service/price/xml.do?action=periodWholesaleProductList&p_startday=2024-08-01&p_endday=2024-08-09&p_itemcategorycode=100&p_itemcode=111&p_kindcode=01&p_productrankcode=04&p_countrycode=1101&p_convert_kg_yn=Y&p_cert_key={CERT_KEY}&p_cert_id={CERT_ID}&p_returntype=xml'
url = 'http://www.kamis.or.kr/service/price/xml.do?action=periodWholesaleProductList&p_startday=2024-08-01&p_endday=2024-08-09&p_itemcategorycode=100&p_itemcode=111&p_kindcode=01&p_productrankcode=04&p_countrycode=1101&p_convert_kg_yn=Y&p_cert_key=111&p_cert_id=222&p_returntype=json'
response = requests.get(url)
response.text

'{"condition":{"item":{"p_startday":"2024-08-01","p_endday":"2024-08-09","p_itemcategorycode":"100","p_itemcode":"111","p_kindcode":"01","p_productrankcode":"04","p_countycode":"1101","p_convert_kg_yn":"Y","p_key":"111","p_id":"222","p_returntype":"json"}},"data":{"error_code":"000","item":[{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/01","price":"2,450"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/02","price":"2,450"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/05","price":"2,450"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/06","price":"2,450"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/07","price":"2,450"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/08","price":"2,420"},{"itemname":null,"kindname":null,"countyname":"평균","marketname":null,"yyyy":"2024","regday":"08/09","price":"2,420"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/01","price":"2,410"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/02","price":"2,415"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/05","price":"2,425"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/06","price":"2,425"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/07","price":"2,425"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/08","price":"2,426"},{"itemname":null,"kindname":null,"countyname":"평년","marketname":null,"yyyy":"2024","regday":"08/09","price":"2,427"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/01","price":"2,450"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/02","price":"2,450"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/05","price":"2,450"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/06","price":"2,450"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/07","price":"2,450"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/08","price":"2,420"},{"itemname":"쌀","kindname":"20kg(1kg)","countyname":"서울","marketname":"양곡도매","yyyy":"2024","regday":"08/09","price":"2,420"}]}}'