In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size="6" color="red"><b>ch14. 웹데이터수집1_정적_공공api</b></font>

# 1절. BeautifulSoup 과 parser
```pip install bs4 - 아나콘다에 설치되어있음```
- 공식사이트 : https://www.crummy.com/software/BeautifulSoup/
- Docs : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [2]:
import requests # http 요청 처리 lib
from requests_file import FileAdapter

In [16]:
s = requests.Session() # http 요청 관리를 위한 세션 객체
s.mount("file://", FileAdapter())
response = s.get("file:///ai_x/source/01_python/data/ch14_sample.html")
response

In [4]:
response.status_code
# 200 : 정상 / 404 : 없는 페이지 / # 406 : get, post 오류

200

In [6]:
ex = response.content  # 바이너리 형식의 내용, 이미지 등을 분석하는데 필요
ex

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [7]:
ex.decode('utf-8')  # 읽을 수 있는 utf-8로 디코딩

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [17]:
response.text  # 위와 같다. 텍스트만 크롤링이 필요하면 앞으로는 이걸로 내용을 읽어올 예정

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [18]:
# html 파싱
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.content,  # == response.text
                    "html.parser")  # html.parser를 이용하면 자동 디코딩이 되네
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [22]:
# soup.select_one('선택자') : 해당 선택자 처음 하나만 가져온다
el = soup.select_one('h1')
print('el : ', el)
print('el.text : ', el.text)
print('el.string : ', el.string)
print('el의 속성들 : ', el.attrs)
print('el의 title 속성 : ', el.attrs['title'])
print('el의 title 속성 : ', el.attrs.get('title'))  # 오류방지를 위해 get 함수 사용 권장
print('el의 이름 : ', el.name)  # 태그 이름을 가져옴

el :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
el.text :  Hello, CSS
el.string :  Hello, CSS
el의 속성들 :  {'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}
el의 title 속성 :  greeting
el의 title 속성 :  greeting
el의 이름 :  h1

In [30]:
# soup.select('선택자') : 해당 선택자 전체 요소를 리스트로 가져온다
el_list = soup.select('h1')
[el.text for el in el_list]
print('el_list : ', el_list)
print('el_list의 텍스트들 : ', [el.text for el in el_list])  # 웹크롤링 할때 리스트컴프리헨션 많이 사용한다
print('el_list의 속성들 : ', [el.attrs for el in el_list]) 
print('el_list의 class속성 : ', [el.attrs.get('class') for el in el_list])

el_list :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
el_list의 텍스트들 :  ['Hello, CSS', 'Hi, CSS']
el_list의 속성들 :  [{'class': ['greeting', 'css'], 'id': 'text', 'title': 'greeting'}, {'class': ['css']}]
el_list의 class속성 :  [['greeting', 'css'], ['css']]

In [32]:
# soup.select_one(선택자) vs find(태그, 속성)
print('select_one : ', soup.select_one('h1.css'))
print('find : ', soup.find('h1', {'class':'css'}))
print('find : ', soup.find('h1', class_='css'))
print()
print('select_one : ', soup.select_one('h1#text'))
print('find : ', soup.find('h1', {'id':'text'}))

select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

select_one :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>
find :  <h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>

In [36]:
# soup.select(선택자) vs find_all(태그, 속성)
print('모든 h1.css, span 태그(select) : ', 
      soup.select('h1.css, span'))
print('모든 h1.css, span 태그(find_all) : ', 
      soup.find_all(['h1', 'span'], {'class':'css'})) # span은 클래스가 없어서 선택되지 않는 문제가 있다

모든 h1.css, span 태그(select) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>, <span>다른<b>요소가 반환</b></span>]
모든 h1.css, span 태그(find_all) :  [<h1 class="greeting css" id="text" title="greeting">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]

In [41]:
# 없는 엘리먼트 찾기 (4가지 방법)
print('find_all : ', soup.find_all('a', class_='css'))  # 빈리스트
print('find : ', soup.find('a', class_='css'))  # None
print('select : ', soup.select('a.css'))  # 빈리스트
print('select_one : ', soup.select_one('a.css'))  # None
# 여러 개를 찾는 함수는 빈리스트로, 한 개를 찾는 함수는 None으로 출력됨을 알 수 있다

find_all :  []
find :  None
select :  []
select_one :  None

# 2절. 정적 웹데이터 수집(정적 웹크롤링)
- json, html, xml
## 2.1 JSON파일
- requests 모듈(get)
- urllib.request모듈(urlopen)
- 실습페이지 - http://api.github.com

In [ ]:
# 크롤링 허용 범위는 사이트마다 다름 ~/robots.txt에서 확인할 수 있다

In [130]:
# 방법2
from urllib.request import urlopen
response = urlopen('http://api.github.com')
response

HTTPError: HTTP Error 403: rate limit exceeded

In [138]:
text = '{"속성1":"값1", "속성2":"값2", "속성3":"값3", "속성4":"값4"}'

In [139]:
# 문자(딕셔너리 타입)를 딕셔너리로
# "{'속성1':'값1', '속성2':'값2', '속성3':'값3', '속성4':'값4'}" => {'속성1':'값1', '속성2':'값2', '속성3':'값3', '속성4':'값4'}
import json
json.loads(text)

{'속성1': '값1', '속성2': '값2', '속성3': '값3', '속성4': '값4'}

## 2.2 html 크롤링
- https://finance.naver.com/marketindex/
- 크롤링 가능범위 확인 : https://finance.naver.com/marketindex/robots.txt
### 1) 네이버증권 시장지표 크롤링 실습
- https://finance.naver.com/marketindex/

In [70]:
# 방법 1 requests.get
import requests
from bs4 import BeautifulSoup
url = 'https://finance.naver.com/marketindex'
response = requests.get(url)
# response, response.status_code
# response.content.decode('cp949') == response.text
soup = BeautifulSoup(response.text, 'html.parser')
soup

<script language="javascript" src="/template/head_js.naver?referer=info.finance.naver.com&amp;menu=marketindex&amp;submenu=market"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/jindo.1.5.3.element-text-patch.js" type="text/javascript"></script>
<div id="container" style="padding-bottom:0px;">
<div class="market_include">
<div class="market_data">
<div class="market1">
<div class="title">
<h2 class="h_market1"><span>환전 고시 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="exchangeList">
<li class="on">
<a class="head usd" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdt', '', '', event);">
<h3 class="h_lst"><span class="blind">미국 USD</span></h3>
<div class="head_info point_dn">
<span class="value">1,374.70</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.30</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head jpy" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyt', '', '', event);">
<h3 class="h_lst"><span class="blind">일본 JPY(100엔)</span></h3>
<div class="head_info point_dn">
<span class="value">952.57</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.76</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head eur" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurt', '', '', event);">
<h3 class="h_lst"><span class="blind">유럽연합 EUR</span></h3>
<div class="head_info point_dn">
<span class="value">1,555.89</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 4.01</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head cny" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyt', '', '', event);">
<h3 class="h_lst"><span class="blind">중국 CNY</span></h3>
<div class="head_info point_dn">
<span class="value">190.99</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.39</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market2">
<div class="title">
<h2 class="h_market2"><span>국제 시장 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="worldExchangeList">
<li class="on">
<a class="head jpy_usd" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyut', '', '', event);">
<h3 class="h_lst"><span class="blind">달러/일본 엔</span></h3>
<div class="head_info point_up">
<span class="value">144.3800</span>
<span class="txt_jpy"><span class="blind">엔</span></span>
<span class="change">1.6000</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyuc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_eur" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdt', '', '', event);">
<h3 class="h_lst"><span class="blind">유로/달러</span></h3>
<div class="head_info point_dn">
<span class="value">1.1342</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.0041</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_gbp" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdt', '', '', event);">
<h3 class="h_lst"><span class="blind">영국 파운드/달러</span></h3>
<div class="head_info point_dn">
<span class="value">1.3520</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.0041</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_idx" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indt', '', '', event);">
<h3 class="h_lst"><span class="blind">달러인덱스</span></h3>
<div class="head_info point_up">
<span class="value">99.4200</span>
<span class="change">0.4100</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">ICE 기준</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market3">
<div class="title">
<h2 class="h_market3"><span>유가·금시세</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="oilGoldList">
<li class="on">
<a class="head wti" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtit', '', '', event);">
<h3 class="h_lst"><span class="blind">WTI</span></h3>
<div class="head_info point_dn">
<span class="value">60.89</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.64</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtic', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">NYMEX(뉴욕상업거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gasoline" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilt', '', '', event);">
<h3 class="h_lst"><span class="blind">휘발유</span></h3>
<div class="head_info point_dn">
<span class="value">1633.17</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.48</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28</span>
<span class="source">한국석유공사 Opinet 기준</span>
</div>
</li>
<li class="">
<a class="head gold_inter" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국제 금</span></h3>
<div class="head_info point_dn">
<span class="value">3300.4</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 65.40</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">COMEX(뉴욕상품거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gold_domestic" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국내 금</span></h3>
<div class="head_info point_up">
<span class="value">146218.18</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">234.29</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:19</span>
<span class="source">신한은행 기준</span>
							(<span class="num">143</span>회차)
					</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
</div>
</div>
<div class="marketindex_content _replaceNewsLink" id="content">
<div class="section_news">
<h3 class="h_market"><span>환율 주요뉴스</span></h3>
<div class="list_area">
<ul>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415417" onclick="clickcr(this, 'mhn.list', '001_0015415417', '0', event);">美소비심리 개선에 달러 강세…환율, 6.0</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:29</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415406" onclick="clickcr(this, 'mhn.list', '001_0015415406', '1', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:23</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415405" onclick="clickcr(this, 'mhn.list', '001_0015415405', '2', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:23</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415404" onclick="clickcr(this, 'mhn.list', '001_0015415404', '3', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:22</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415401" onclick="clickcr(this, 'mhn.list', '001_0015415401', '4', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415400" onclick="clickcr(this, 'mhn.list', '001_0015415400', '5', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415399" onclick="clickcr(this, 'mhn.list', '001_0015415399', '6', event);">환율 오름세로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415398" onclick="clickcr(this, 'mhn.list', '001_0015415398', '7', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415397" onclick="clickcr(this, 'mhn.list', '001_0015415397', '8', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415396" onclick="clickcr(this, 'mhn.list', '001_0015415396', '9', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
</ul>
</div>
<a class="btn_more" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429" onclick="clickcr(this, 'mhn.more', '', '', event);"><img alt="더보기" height="18" src="https://ssl.pstatic.net/static/nfinance/btn_more.gif" width="34"/></a>
</div>
<div class="tab_default1" id="tab_section">
<ul>
<li class="on"><a href="./?tabSel=exchange#tab_section" onclick="clickcr(this, 'mtb.exnoti', '', '', event);"><span class="tab1">환전고시 환율</span></a></li>
<li class=""><a href="./?tabSel=worldExchange#tab_section" onclick="clickcr(this, 'mtb.interex', '', '', event);"><span class="tab2">국제시장 환율</span></a></li>
<li class=""><a href="./?tabSel=gold#tab_section" onclick="clickcr(this, 'mtb.oilgold', '', '', event);"><span class="tab3">유가 금시세</span></a></li>
<li class=""><a href="./?tabSel=materials#tab_section" onclick="clickcr(this, 'mtb.material', '', '', event);"><span class="tab4">원자재</span></a></li>
</ul>
<h2 class="blind">환전고시 환율</h2>
</div>
<div class="section_calculator">
<h3 class="h_calculator"><span>환율계산기 (매매기준율 기준)</span></h3>
<div class="calculator">
<div class="inner">
<div class="input">
<div class="selectbox-noscript" id="sInput">
<select class="selectbox-source" id="select_from">
<option label="1" value="1">대한민국 원 KRW</option>
<option class="selectbox-default" label="1" selected="selected" value="1374.7"> 미국 달러 USD</option>
<option label="1" value="1374.7"> 미국 달러 USD</option>
<option label="1" value="1555.89"> 유럽연합 유로 EUR</option>
<option label="100" value="9.5257"> 일본 엔 JPY</option>
<option label="1" value="190.99"> 중국 위안 CNY</option>
<option label="1" value="175.35"> 홍콩 달러 HKD</option>
<option label="1" value="45.94"> 대만 달러 TWD</option>
<option label="1" value="1855.23"> 영국 파운드 GBP</option>
<option label="1" value="3570.83"> 오만 리알 OMR</option>
<option label="1" value="994.57"> 캐나다 달러 CAD</option>
<option label="1" value="1660.77"> 스위스 프랑 CHF</option>
<option label="1" value="142.72"> 스웨덴 크로나 SEK</option>
<option label="1" value="885.44"> 호주 달러 AUD</option>
<option label="1" value="819.11"> 뉴질랜드 달러 NZD</option>
<option label="1" value="62.47"> 체코 코루나 CZK</option>
<option label="1" value="1.47"> 칠레 페소 CLP</option>
<option label="1" value="35.18"> 튀르키예 뉴리라 TRY</option>
<option label="1" value="0.38"> 몽골 투그릭 MNT</option>
<option label="1" value="389.05"> 이스라엘 세켈 ILS</option>
<option label="1" value="208.66"> 덴마크 크로네 DKK</option>
<option label="1" value="135.15"> 노르웨이 크로네 NOK</option>
<option label="1" value="366.5"> 사우디아라비아 리얄 SAR</option>
<option label="1" value="4481.94"> 쿠웨이트 디나르 KWD</option>
<option label="1" value="3646.42"> 바레인 디나르 BHD</option>
<option label="1" value="374.32"> 아랍에미리트 디르함 AED</option>
<option label="1" value="1938.93"> 요르단 디나르 JOD</option>
<option label="1" value="27.6"> 이집트 파운드 EGP</option>
<option label="1" value="41.99"> 태국 바트 THB</option>
<option label="1" value="1066.32"> 싱가포르 달러 SGD</option>
<option label="1" value="323.38"> 말레이시아 링깃 MYR</option>
<option label="100" value="0.0843"> 인도네시아 루피아 IDR</option>
<option label="1" value="377.25"> 카타르 리얄 QAR</option>
<option label="1" value="2.69"> 카자흐스탄 텡게 KZT</option>
<option label="1" value="1066.32"> 브루나이 달러 BND</option>
<option label="1" value="16.11"> 인도 루피 INR</option>
<option label="1" value="4.86"> 파키스탄 루피 PKR</option>
<option label="1" value="11.26"> 방글라데시 타카 BDT</option>
<option label="1" value="24.72"> 필리핀 페소 PHP</option>
<option label="1" value="71.33"> 멕시코 페소 MXN</option>
<option label="1" value="243.82"> 브라질 레알 BRL</option>
<option label="100" value="0.053"> 베트남 동 VND</option>
<option label="1" value="76.57"> 남아프리카 공화국 랜드 ZAR</option>
<option label="1" value="17.13"> 러시아 루블 RUB</option>
<option label="1" value="3.85"> 헝가리 포린트 HUF</option>
<option label="1" value="366.26"> 폴란드 즈워티 PLN</option>
<option label="1" value="4.59"> 스리랑카 루피 LKR</option>
<option label="1" value="10.41"> 알제리 알제리 디나르 DZD</option>
<option label="1" value="10.64"> 케냐 실링 KES</option>
<option label="1" value="0.33"> 콜롬비아 페소 COP</option>
<option label="1" value="0.51"> 탄자니아 실링 TZS</option>
<option label="1" value="10.07"> 네팔 루피 NPR</option>
<option label="1" value="307.91"> 루마니아 레우 RON</option>
<option label="1" value="252.29"> 리비아 리비아 디나르 LYD</option>
<option label="1" value="170.14"> 마카오 파타카 MOP</option>
<option label="1" value="0.65"> 미얀마 짯 MMK</option>
<option label="1" value="10.05"> 에티오피아 비르 ETB</option>
<option label="1" value="0.11"> 우즈베키스탄 숨 UZS</option>
<option label="1" value="0.34"> 캄보디아 리엘 KHR</option>
<option label="1" value="607.96"> 피지 피지 달러 FJD</option>
</select>
<div class="selectbox-box" onclick="clickcr(this, 'exl*c.clist1', '', '', event);">
<div class="selectbox-label"></div>
</div>
<div class="selectbox-layer ly_calculator">
<div class="selectbox-list"></div>
</div>
</div>
<div class="input_area" id="input_from">
<input id="input_from_money" maxlength="10" onclick="clickcr(this, 'exl*c.unit1', '', '', event);" onfocus="changeActiveInput('from', 'to'); return false;" onkeyup="calcExchange('from', 'to', 'on', event);" type="text" value="1"/>
<img alt="" height="13" id="img_from_monetary" src="https://ssl.pstatic.net/static/nfinance/img_money_USD.gif" width="26"/>
</div>
</div>
<div class="same"><img alt="" height="15" src="https://ssl.pstatic.net/static/nfinance/ico_same.gif" width="28"/></div>
<div class="view">
<div class="selectbox-noscript" id="sView">
<select class="selectbox-source" id="select_to">
<option class="selectbox-default" label="1" value="1">대한민국 원 KRW</option>

In [69]:
# 방법 2 urlopen
from urllib.request import urlopen
response = urlopen(url)
# response, response.status # 상태코드
# response.read()  # requests의 content 와 동일
# response.read().decode('cp949')  # requests의 text 와 동일
soup = BeautifulSoup(response, 'html.parser')
soup

<script language="javascript" src="/template/head_js.naver?referer=info.finance.naver.com&amp;menu=marketindex&amp;submenu=market"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20250522145100/js/jindo.1.5.3.element-text-patch.js" type="text/javascript"></script>
<div id="container" style="padding-bottom:0px;">
<div class="market_include">
<div class="market_data">
<div class="market1">
<div class="title">
<h2 class="h_market1"><span>환전 고시 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="exchangeList">
<li class="on">
<a class="head usd" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdt', '', '', event);">
<h3 class="h_lst"><span class="blind">미국 USD</span></h3>
<div class="head_info point_dn">
<span class="value">1,374.70</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.30</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head jpy" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyt', '', '', event);">
<h3 class="h_lst"><span class="blind">일본 JPY(100엔)</span></h3>
<div class="head_info point_dn">
<span class="value">952.57</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.76</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head eur" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurt', '', '', event);">
<h3 class="h_lst"><span class="blind">유럽연합 EUR</span></h3>
<div class="head_info point_dn">
<span class="value">1,555.89</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 4.01</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
<li class="">
<a class="head cny" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyt', '', '', event);">
<h3 class="h_lst"><span class="blind">중국 CNY</span></h3>
<div class="head_info point_dn">
<span class="value">190.99</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.39</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:22</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">275</span>회</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market2">
<div class="title">
<h2 class="h_market2"><span>국제 시장 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="worldExchangeList">
<li class="on">
<a class="head jpy_usd" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyut', '', '', event);">
<h3 class="h_lst"><span class="blind">달러/일본 엔</span></h3>
<div class="head_info point_up">
<span class="value">144.3800</span>
<span class="txt_jpy"><span class="blind">엔</span></span>
<span class="change">1.6000</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyuc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_eur" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdt', '', '', event);">
<h3 class="h_lst"><span class="blind">유로/달러</span></h3>
<div class="head_info point_dn">
<span class="value">1.1342</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.0041</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_gbp" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdt', '', '', event);">
<h3 class="h_lst"><span class="blind">영국 파운드/달러</span></h3>
<div class="head_info point_dn">
<span class="value">1.3520</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.0041</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_idx" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indt', '', '', event);">
<h3 class="h_lst"><span class="blind">달러인덱스</span></h3>
<div class="head_info point_up">
<span class="value">99.4200</span>
<span class="change">0.4100</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">ICE 기준</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market3">
<div class="title">
<h2 class="h_market3"><span>유가·금시세</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="oilGoldList">
<li class="on">
<a class="head wti" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtit', '', '', event);">
<h3 class="h_lst"><span class="blind">WTI</span></h3>
<div class="head_info point_dn">
<span class="value">60.89</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 0.64</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtic', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">NYMEX(뉴욕상업거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gasoline" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilt', '', '', event);">
<h3 class="h_lst"><span class="blind">휘발유</span></h3>
<div class="head_info point_dn">
<span class="value">1633.17</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 0.48</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28</span>
<span class="source">한국석유공사 Opinet 기준</span>
</div>
</li>
<li class="">
<a class="head gold_inter" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국제 금</span></h3>
<div class="head_info point_dn">
<span class="value">3300.4</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change"> 65.40</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.27</span>
<span class="source">COMEX(뉴욕상품거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gold_domestic" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국내 금</span></h3>
<div class="head_info point_up">
<span class="value">146218.18</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">234.29</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2025.05.28 11:19</span>
<span class="source">신한은행 기준</span>
							(<span class="num">143</span>회차)
					</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
</div>
</div>
<div class="marketindex_content _replaceNewsLink" id="content">
<div class="section_news">
<h3 class="h_market"><span>환율 주요뉴스</span></h3>
<div class="list_area">
<ul>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415417" onclick="clickcr(this, 'mhn.list', '001_0015415417', '0', event);">美소비심리 개선에 달러 강세…환율, 6.0</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:29</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415406" onclick="clickcr(this, 'mhn.list', '001_0015415406', '1', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:23</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415405" onclick="clickcr(this, 'mhn.list', '001_0015415405', '2', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:23</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415404" onclick="clickcr(this, 'mhn.list', '001_0015415404', '3', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:22</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415401" onclick="clickcr(this, 'mhn.list', '001_0015415401', '4', event);">코스피, 환율 오름세 출발</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415400" onclick="clickcr(this, 'mhn.list', '001_0015415400', '5', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415399" onclick="clickcr(this, 'mhn.list', '001_0015415399', '6', event);">환율 오름세로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415398" onclick="clickcr(this, 'mhn.list', '001_0015415398', '7', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415397" onclick="clickcr(this, 'mhn.list', '001_0015415397', '8', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429&amp;office_id=001&amp;article_id=0015415396" onclick="clickcr(this, 'mhn.list', '001_0015415396', '9', event);">코스피·코스닥지수 강보합으로 거래 시작</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>05.28 09:21</span>
</li>
</ul>
</div>
<a class="btn_more" href="/news/news_list.naver?mode=LSS3D§ion_id=101§ion_id2=258§ion_id3=429" onclick="clickcr(this, 'mhn.more', '', '', event);"><img alt="더보기" height="18" src="https://ssl.pstatic.net/static/nfinance/btn_more.gif" width="34"/></a>
</div>
<div class="tab_default1" id="tab_section">
<ul>
<li class="on"><a href="./?tabSel=exchange#tab_section" onclick="clickcr(this, 'mtb.exnoti', '', '', event);"><span class="tab1">환전고시 환율</span></a></li>
<li class=""><a href="./?tabSel=worldExchange#tab_section" onclick="clickcr(this, 'mtb.interex', '', '', event);"><span class="tab2">국제시장 환율</span></a></li>
<li class=""><a href="./?tabSel=gold#tab_section" onclick="clickcr(this, 'mtb.oilgold', '', '', event);"><span class="tab3">유가 금시세</span></a></li>
<li class=""><a href="./?tabSel=materials#tab_section" onclick="clickcr(this, 'mtb.material', '', '', event);"><span class="tab4">원자재</span></a></li>
</ul>
<h2 class="blind">환전고시 환율</h2>
</div>
<div class="section_calculator">
<h3 class="h_calculator"><span>환율계산기 (매매기준율 기준)</span></h3>
<div class="calculator">
<div class="inner">
<div class="input">
<div class="selectbox-noscript" id="sInput">
<select class="selectbox-source" id="select_from">
<option label="1" value="1">대한민국 원 KRW</option>
<option class="selectbox-default" label="1" selected="selected" value="1374.7"> 미국 달러 USD</option>
<option label="1" value="1374.7"> 미국 달러 USD</option>
<option label="1" value="1555.89"> 유럽연합 유로 EUR</option>
<option label="100" value="9.5257"> 일본 엔 JPY</option>
<option label="1" value="190.99"> 중국 위안 CNY</option>
<option label="1" value="175.35"> 홍콩 달러 HKD</option>
<option label="1" value="45.94"> 대만 달러 TWD</option>
<option label="1" value="1855.23"> 영국 파운드 GBP</option>
<option label="1" value="3570.83"> 오만 리알 OMR</option>
<option label="1" value="994.57"> 캐나다 달러 CAD</option>
<option label="1" value="1660.77"> 스위스 프랑 CHF</option>
<option label="1" value="142.72"> 스웨덴 크로나 SEK</option>
<option label="1" value="885.44"> 호주 달러 AUD</option>
<option label="1" value="819.11"> 뉴질랜드 달러 NZD</option>
<option label="1" value="62.47"> 체코 코루나 CZK</option>
<option label="1" value="1.47"> 칠레 페소 CLP</option>
<option label="1" value="35.18"> 튀르키예 뉴리라 TRY</option>
<option label="1" value="0.38"> 몽골 투그릭 MNT</option>
<option label="1" value="389.05"> 이스라엘 세켈 ILS</option>
<option label="1" value="208.66"> 덴마크 크로네 DKK</option>
<option label="1" value="135.15"> 노르웨이 크로네 NOK</option>
<option label="1" value="366.5"> 사우디아라비아 리얄 SAR</option>
<option label="1" value="4481.94"> 쿠웨이트 디나르 KWD</option>
<option label="1" value="3646.42"> 바레인 디나르 BHD</option>
<option label="1" value="374.32"> 아랍에미리트 디르함 AED</option>
<option label="1" value="1938.93"> 요르단 디나르 JOD</option>
<option label="1" value="27.6"> 이집트 파운드 EGP</option>
<option label="1" value="41.99"> 태국 바트 THB</option>
<option label="1" value="1066.32"> 싱가포르 달러 SGD</option>
<option label="1" value="323.38"> 말레이시아 링깃 MYR</option>
<option label="100" value="0.0843"> 인도네시아 루피아 IDR</option>
<option label="1" value="377.25"> 카타르 리얄 QAR</option>
<option label="1" value="2.69"> 카자흐스탄 텡게 KZT</option>
<option label="1" value="1066.32"> 브루나이 달러 BND</option>
<option label="1" value="16.11"> 인도 루피 INR</option>
<option label="1" value="4.86"> 파키스탄 루피 PKR</option>
<option label="1" value="11.26"> 방글라데시 타카 BDT</option>
<option label="1" value="24.72"> 필리핀 페소 PHP</option>
<option label="1" value="71.33"> 멕시코 페소 MXN</option>
<option label="1" value="243.82"> 브라질 레알 BRL</option>
<option label="100" value="0.053"> 베트남 동 VND</option>
<option label="1" value="76.57"> 남아프리카 공화국 랜드 ZAR</option>
<option label="1" value="17.13"> 러시아 루블 RUB</option>
<option label="1" value="3.85"> 헝가리 포린트 HUF</option>
<option label="1" value="366.26"> 폴란드 즈워티 PLN</option>
<option label="1" value="4.59"> 스리랑카 루피 LKR</option>
<option label="1" value="10.41"> 알제리 알제리 디나르 DZD</option>
<option label="1" value="10.64"> 케냐 실링 KES</option>
<option label="1" value="0.33"> 콜롬비아 페소 COP</option>
<option label="1" value="0.51"> 탄자니아 실링 TZS</option>
<option label="1" value="10.07"> 네팔 루피 NPR</option>
<option label="1" value="307.91"> 루마니아 레우 RON</option>
<option label="1" value="252.29"> 리비아 리비아 디나르 LYD</option>
<option label="1" value="170.14"> 마카오 파타카 MOP</option>
<option label="1" value="0.65"> 미얀마 짯 MMK</option>
<option label="1" value="10.05"> 에티오피아 비르 ETB</option>
<option label="1" value="0.11"> 우즈베키스탄 숨 UZS</option>
<option label="1" value="0.34"> 캄보디아 리엘 KHR</option>
<option label="1" value="607.96"> 피지 피지 달러 FJD</option>
</select>
<div class="selectbox-box" onclick="clickcr(this, 'exl*c.clist1', '', '', event);">
<div class="selectbox-label"></div>
</div>
<div class="selectbox-layer ly_calculator">
<div class="selectbox-list"></div>
</div>
</div>
<div class="input_area" id="input_from">
<input id="input_from_money" maxlength="10" onclick="clickcr(this, 'exl*c.unit1', '', '', event);" onfocus="changeActiveInput('from', 'to'); return false;" onkeyup="calcExchange('from', 'to', 'on', event);" type="text" value="1"/>
<img alt="" height="13" id="img_from_monetary" src="https://ssl.pstatic.net/static/nfinance/img_money_USD.gif" width="26"/>
</div>
</div>
<div class="same"><img alt="" height="15" src="https://ssl.pstatic.net/static/nfinance/ico_same.gif" width="28"/></div>
<div class="view">
<div class="selectbox-noscript" id="sView">
<select class="selectbox-source" id="select_to">
<option class="selectbox-default" label="1" value="1">대한민국 원 KRW</option>

In [103]:
# 분석
# title => h3.h_lst > span.blind
# price => div.head_info > span.value
# unit => div.head_info > span > span.blind
# status => div.head_info > span.blind
title = soup.select('h3.h_lst > span.blind')
title = [t.text for t in title]
price = soup.select('div.head_info > span.value')
price = [float(p.text.replace(',','')) for p in price]
unit = soup.select('div.head_info > span > span.blind')
unit = [u.text for u in unit]
unit.insert(7,'')  # 7번째인 달러인덱스에는 단위가 없어 빈값 삽입
status = soup.select('div.head_info > span.blind')
status = [s.text for s in status]
status

['하락', '하락', '하락', '하락', '상승', '하락', '하락', '상승', '하락', '하락', '하락', '상승']

In [96]:
for idx in range(len(title)):
    print('{} : {}{} - {}'.format(title[idx], 
                                  price[idx], 
                                  unit[idx], 
                                  status[idx]))

미국 USD : 1374.7원 - 하락
일본 JPY(100엔) : 952.57원 - 하락
유럽연합 EUR : 1555.89원 - 하락
중국 CNY : 190.99원 - 하락
달러/일본 엔 : 144.38엔 - 상승
유로/달러 : 1.1342달러 - 하락
영국 파운드/달러 : 1.352달러 - 하락
달러인덱스 : 99.42 - 상승
WTI : 60.89달러 - 하락
휘발유 : 1633.17원 - 하락
국제 금 : 3300.4달러 - 하락
국내 금 : 146218.18원 - 상승

In [108]:
for idx, (t, p, u, s) in enumerate(zip(title, price, unit, status)):
    print(f'{idx+1}. {t} : {p}{u} - {s}')

1. 미국 USD : 1374.7원 - 하락
2. 일본 JPY(100엔) : 952.57원 - 하락
3. 유럽연합 EUR : 1555.89원 - 하락
4. 중국 CNY : 190.99원 - 하락
5. 달러/일본 엔 : 144.38엔 - 상승
6. 유로/달러 : 1.1342달러 - 하락
7. 영국 파운드/달러 : 1.352달러 - 하락
8. 달러인덱스 : 99.42 - 상승
9. WTI : 60.89달러 - 하락
10. 휘발유 : 1633.17원 - 하락
11. 국제 금 : 3300.4달러 - 하락
12. 국내 금 : 146218.18원 - 상승

### 2) 동행복권 크롤링 실습
- https://dhlottery.co.kr/gameResult.do?method=byWin

In [145]:
# 방법 1
response = requests.get('https://dhlottery.co.kr/gameResult.do?method=byWin')
soup = BeautifulSoup(response.text, 'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [163]:
# 사이트 분석 
# 회차 turn = div.win_result > h4 > strong
# 날짜 date = div.win_result > p.desc'
# 당첨번호 = div.win > strong
# nums = div.win > p > span / 
# 보너스번호 = div.bonus > strong
# bonus = div.bonus > p > span
turn = soup.select_one('div.win_result > h4 > strong')
date = soup.select_one('div.win_result > p.desc')
n_title = soup.select_one('div.num.win > strong')
nums = soup.select('div.num.win > p > span')
b_title = soup.select_one('div.num.bonus > strong')
bonus = soup.select_one('div.num.bonus > p > span')
num = [int(n.text) for n in nums]
print('{}{}'.format(turn.text, date.text))
print('{} {}'.format(n_title.text, num))
print('{} {}'.format(b_title.text, bonus.text))

1173회(2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

In [164]:
# 방법 2
response = urlopen('https://dhlottery.co.kr/gameResult.do?method=byWin')
soup = BeautifulSoup(response, 'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="동행복권" id="utitle" name="title"/>
<meta content="동행복권 1173회 당첨번호 1,5,18,20,30,35+3. 1등 총 24명, 1인당 당첨금액 1,179,946,063원." id="desc" name="description"/>
<title>로또6/45 - 회차별 당첨번호</title>
<title>동행복권</title>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<link href="/images/common/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/images/common/favicon.ico" rel="icon" type="image/x-icon"/>
<script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-ui.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/common.js" type="text/javascript"></script>
<script type="text/javascript">

fn_g_init_message("");

var gameUserId = "";

function goGame(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert('접속이 원활하지 않습니다.');
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp("");
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGame(lottoId,agreeType){
	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGamePnInfo(lottoId,agreeType,svcInfoPnPcMsgYn){
	var svcInfoPnPcMsgYn = svcInfoPnPcMsgYn;

	if (svcInfoPnPcMsgYn == "Y") {
		svcInfoPnMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElInfo(lottoId,agreeType,svcInfoElPcMsgYn){
	var lottoId = lottoId;
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;

	// 2024 연마감 관련 코드
	if (svcInfoElPcMsgYn == "Y") {
		if (lottoId == "LI21") {	//20241226 sicc_kic 2024년도 트리플럭 판매종료.
			svcInfoElTrMsg();
			return;
		}
		else if (lottoId == "LI22") {  //20241125 sicc_kic 2024년도 트레져헌터 판매종료.
			svcInfoElThMsg();
			return;
		}
		else if (lottoId == "LI23") {  //20241226 sicc_kic 2024년도 캐치미 판매종료.
			svcInfoElCmMsg();
			return;
		}
		else if (lottoId == "LD10") {  //20241125 sicc_kjh 2024년도 스피드키노 판매종료.
		    svcInfoElSkMsg();
			return;
		}
		else if (lottoId == "LD11") {  //20241112 sicc_khj 2024년도 메가빙고 판매종료.
			svcInfoElMbMsg();
			return;
		}
		else if (lottoId == "LD14") {  //20241125 sicc_kic 2024년도 파워볼 판매종료.
			svcInfoElPbMsg();
			return;
		}
		else if (lottoId == "LD20") {  //20241226 sicc_kic 2024년도 더블잭  판매종료.
			svcInfoElDmMsg();
			return;
		}
		else {
			svcInfoElMsg();
			return;
		}
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameEnInfo(lottoId,agreeType,endInfoElPcMsgYn){
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function goGameElEnInfo(lottoId,agreeType,svcInfoElPcMsgYn,endInfoElPcMsgYn){
	var svcInfoElPcMsgYn = svcInfoElPcMsgYn;
	var endInfoElPcMsgYn = endInfoElPcMsgYn;

	//2023연마감 관련 코드 (캐치미,트래져헌터 조기종료로 추가된코드.)
	if("N" == "Y"){
		if(lottoId == "LI23" || lottoId == "LI22" ) {
			//LI23: 캐치미,  LI22트레져헌터
			svcInfoElMsgEx();
			return;
		}
	}

	if (svcInfoElPcMsgYn == "Y") {
			svcInfoElMsg();
			return;
	}

	if (endInfoElPcMsgYn == "Y") {
		endInfoElMsg();
		return;
	}

	var userId = "";
	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + lottoId);
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",  	// url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		timeout:3000,
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수

			if(userId == data.userId && data.userId != ""){
				doGamePopUp(lottoId,agreeType);
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

function doGamePopUp(lotid,agreeType){
	/*
	* 스피드키노 LD10, 메가빙고 LD11, 더블잭마이더스 LD20, 파워볼 LD14, 트레져헌터 LI22, 트리플럭 LI21 -> gamePop
	* 캐치미 LI23 -> catchPop
	*/
	var type;

	if( lotid === 'LI23' ){
		type = 'catchPop';
	}else{
		type = 'gamePop';
	}

	if($("#agreeChk").is(":checked") || agreeType == 2){
		var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId='+ lotid, 'type', 1164, 645, 'no');
	}else{
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
	}

}

//설문조사 팝업
function popCenter(url){
	var new_popup =	centerPop(url, '설문조사', 480, 800, 'yes');
}

//샘플게임 팝업
function sample_pop(code, userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		//location.href = "/user.do?method=login";
		//location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
		location.href = "/user.do?method=login&returnUrl=" + encodeURIComponent('/gameInfo.do?method=lottoMainView&lottoId=' + code);
		return;
	}
	if(!$("#sampleAgreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#sampleAgreeChk").focus();
		return;
	}

	$.ajax({
		type:"POST",                            // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code, 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}

//샘플게임(랜덤) 팝업
function sample_random_pop(userId){

	//location.href = "/gamezone.do?method=gameZoneMainView";
	//return;
	if(userId == null || userId == ""){
		alert("로그인 후 이용이 가능합니다.");
		location.href = "/user.do?method=login";
// 		location.href = "/user.do?method=login&returnUrl=/gamezone.do?method=gameZoneMainView";
// 		location.href = "/common.do?method=main";
		return;
	}

	var x = Math.floor((Math.random() * 7) + 1 );

	if(x == 1){
		var code = "LD14";
	}else if(x == 2){
		var code = "LD10";
	}else if(x == 3){
		var code = "LD20";
	}else if(x == 4){
		var code = "LI23";
	}else if(x == 5){
		var code = "LI22";
	}else if(x == 6){
		var code = "LI21";
	}else if(x == 7){
		var code = "LD11";
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"/gamezone.do?method=autoAgreeProc",// url
		dataType:"json",                        // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		async:false,
		contentType : "application/json; charset=EUC-KR",
		error: function() {                     // 에러날경우 콜백함수
			console.log("error");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(data.successYn){
				console.log(data);
			}
		}
	});

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		//data:{"jackpot":strJackpotData},   	// 파라메터 타입
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup =	centerPop('https://el.dhlottery.co.kr/game_sample/TotalGame.jsp?LottoId=' + code , 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});
}



function doReserve(){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=game720Method";
		return;
	}

	$.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
					window.open('https://el.dhlottery.co.kr/lotto720.do?method=reserveBuy', 'pensionPop' , 'width=930, height=672, left=0, top=0, status=no, toolbar=no, menubar=no, location=no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}


function jackpotViewPop(){
	var url = "/gameInfo.do?method=jackpotView&lottoId=";
	commonPop("", url, 820, 700, 'yes');
}

function goLottoBuy(agreeType){
	var userId = "";

	if(userId == '' || userId == null){
		alert("로그인 후 사용 해주시기 바랍니다.");
		//location.href = "/user.do?method=login";
		location.href = "/user.do?method=login&returnUrl=/gameInfo.do?method=buyLotto";
		return;
	}
	if(agreeType == 1 && !$("#agreeChk").is(":checked")){
		alert('약관에 동의해 주셔야 이용이 가능합니다.');
		$("#agreeChk").focus();
		return;
	}


	 $.ajax({
		type:"get",                             // 메소드타입
		url:"https://el.dhlottery.co.kr/portal_login.jsp",    // url
		dataType:"jsonp",                       // 이부분이 중요 데이타타입을 jsonP로 해줘야 크로스도메인을 이용할수 있다.
		timeout:3000,
		jsonp : 'callback',                     // 콜백함수 이름 명이다.
		error: function() {                     // 에러날경우 콜백함수
			alert("시스템이 원활하지 않습니다.\n이용에 불편을 드려 죄송합니다.");
		},
		success: function(data){        		// 성공했을때 콜백함수
			if(userId == data.userId && data.userId != ""){
				var new_popup = centerPop('https://el.dhlottery.co.kr/game/TotalGame.jsp?LottoId=LO40', 'gamePop', 1164, 645, 'no');
			}else{
				alert("로그인 세션이 해제 되었습니다.\n다시 한번 로그인해 주시기 바랍니다.");
				document.location.href = "/user.do?method=logout";
			}
	}});

}

function loginType(pageCode){
	var userId = "";
	var pageCodes = pageCode.split("-");
}

//엔터만 치면 로그인
function enter_check_top(eventValue) {
	if (eventValue == 13) {
		check_if_Valid_top();
		return;
	}
}

function depositAlert(){
	alert("12월 2일 이후부터 사용 가능합니다.");
}

function check_if_Valid_top() {
	var f = document.frmLogin;

	if (f.userId.value == "") {
		alert("아이디를 입력해 주십시오");
		f.userId.focus();
		return;
	}
	if (f.password.value == "") {
		alert("비밀번호를 입력해 주세요");
		f.password.focus();
		return;
	}
	if (f.userId.value.length >= 15) {
		alert("아이디가 자릿수가 초과되었습니다.");
		return;
	}
	if (f.password.value.length >= 101) {
		alert("비밀번호가 자릿수가 초과되었습니다.");
		return;
	}
	loginpage_top();
}

function loginpage_top(){

	var f = window.document.frmLogin;
	var pageUrl = document.location.href;
	var returnUrl="";

	f.method = "post";
	//f.target = "jform";
	if(returnUrl != ''){
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(returnUrl);
	}else{
		f.action = "https://www.dhlottery.co.kr/userSsl.do?method=login&returnUrl="+encodeURIComponent(pageUrl);
	}
	f.submit();

}

function getCookie(uName) {
	var flag = document.cookie.indexOf(uName + '=');
	if (flag != -1) {
		flag += uName.length + 1;
		end = document.cookie.indexOf(';', flag);
		if (end == -1)
			end = document.cookie.length;
		return unescape(document.cookie.substring(flag, end));
	}
}

function gomain() {
	location.href="/common.do?method=main";
}

$(document).ready(function() {
	$("#phoneTopMenu").html("");

	if(getCookie("userId") != undefined)
	{
		$('.top_userid').val(getCookie("userId"));
	}

});

function svcInfoPnMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2024년 12월 31일 10시\n재개 일시 : 2025년 01월 02일");
}


function svcInfoElMsg() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 31일 09시\n재개 일시 : 2024년 01월 02일 10시");
}

//연마감용 메시지
function svcInfoElMsgEx() {
	alert("일시 판매정지 중입니다.\n\n정지 일시 : 2023년 12월 05일 00시\n재개 일시 : 2024년 01월 02일 10시");
}

//20241112 sicc_khj 2024년도 메가빙고 판매종료.
function svcInfoElMbMsg() {
	alert("메가빙고 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 11월 13일 00시 \n판매재개 일시 : 2025년 01월 02일 ");
}

// 20241125 sicc_kic 2024년도 파워볼 판매종료.
function svcInfoElPbMsg() {
	alert("파워볼 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 16일 00시 \n판매재개 일시 : 2025년 01월 02일");
}
//20241212 sicc_kic 2024년도 트레져헌터 판매종료.
function svcInfoElThMsg() {
	alert("트레져헌터 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241217 sicc_kjh 2024년도 스피드키노 판매종료.
function svcInfoElSkMsg() {
	alert("스피드키노 복권은 판매종료 합니다.\n\n판매종료 일시 : 2024년 12월 23일 00시 \n판매재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 트리플럭 판매종료.
//--25회차 수정
function svcInfoElTrMsg() {
	alert("트리플럭 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일");
}

//20241226 sicc_kic 2024년도 더블잭 판매종료.
function svcInfoElDmMsg() {
	alert("더블잭 마이더스 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}

//20241226 sicc_kic 2024년도 캐치미 판매종료.
function svcInfoElCmMsg() {
	alert("캐치미 복권은 판매 정지 중입니다.\n\n정지일시 : 2024년 12월 31일 10시 \n재개 일시 : 2025년 01월 02일 ");
}
function endInfoElMsg() {
	alert("판매시간이 아닙니다.\n\n판매 시간 : 06시 ~ 24시");
}

</script>
<!-- <link rel="stylesheet" type="text/css" href="/css/nanum_gothic_dev.css" /> -->
<link href="/css/styles.css" rel="stylesheet" type="text/css"/>
<script charset="utf-8" src="/js/function.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/InsertFlash.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/link.js" type="text/javascript"></script>
<script charset="utf-8" src="/js/makePCookie.js" type="text/javascript"></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/webfont.js" type="text/javascript"></script>
<script>
if (navigator.platform && /win16|win32|win64|mac/ig.test(navigator.platform) == false) {
	if ('https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 || 'https://m.dhlottery.co.kr'.indexOf(location.hostname) == -1 ) {
	  	location.href = 'https://m.dhlottery.co.kr';
	}
}
</script>
<script>
var pageCode = "03-01-01";
var pageName = "회차별 당첨번호";

var hdrw = 1;
function search() {
	$('#drwNo').val($("#dwrNoList").val());
	$("#frm").attr({action:"/gameResult.do?method=byWin", method:"post"}).submit();
}

$(document).ready(function() {

	if("1173" != ""){
		$("#dwrNoList").val("1173");
		if ("1173" < 601) hdrw = 2;
	}
	$('#searchBtn').click(function(e) {
		search();
	});
	$('#printBtn').click(function(e) {
		e.preventDefault();
		commonPop("stat_pop", "/gameResult.do?method=allWinPrint&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val(), "800", "750", "");
	});
	$('#exelBtn').click(function(e) {
		var search1 = $("#drwNoStart").val();
		var search2 = $("#drwNoEnd").val();
		if(parseInt(search2) < parseInt(search1)){
			alert("시작회차가 종료회차보다 큽니다.");
			$('#drwNoEnd').focus();
			return false;
		};
		location.href = "/gameResult.do?method=allWinExel&gubun=byWin&nowPage="+$("#nowPage").val()+"&drwNoStart="+$("#drwNoStart").val()+"&drwNoEnd="+$("#drwNoEnd").val();
	});
	$('#hdrwComb').click(function(e) {
		if($('#hdrwComb').val() != hdrw) {
			hdrw = $('#hdrwComb').val();
			$("#dwrNoList").empty();
			$("#drwNoStart").empty();
			$("#drwNoEnd").empty();
			var str = "";

			if(hdrw == 1) {

In [184]:
# find, find_all 이용
# 사이트 분석 
# 회차 turn = div.win_result > h4 > strong
# 날짜 date = div.win_result > p.desc'
# 당첨번호 n_title = div.win > strong
# nums = div.win > p > span 
# 보너스번호 b_title = div.bonus > strong
# bonus = div.bonus > p > span
turn = soup.find('div', class_='win_result').find('h4').find('strong').text
date = soup.find('div', class_='win_result').find('p', class_='desc').text
n_title = soup.find('div', class_='win').find('strong').text
nums = soup.find('div', class_='win').find('p').find_all('span')
num = [int(n.text) for n in nums]
b_title = soup.find('div', class_='bonus').find('strong').text
bonus = int(soup.find('div', class_='bonus').find('p').find('span').text)
print(f'{turn} {date}')
print(f'{n_title} {num}')
print(f'{b_title} {bonus}')

1173회 (2025년 05월 24일 추첨)
당첨번호 [1, 5, 18, 20, 30, 35]
보너스 3

### 3) daum 검색 리스트(뉴스페이지)

In [191]:
# 방법 1-1. 딕셔너리 리스트
import requests
from bs4 import BeautifulSoup
keyword = '비트코인'
url = "https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q="+keyword
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
itmes_find_list = [] # 검색할 결과를 담을 딕셔너리 리스트

In [207]:
# 사이트 분석
# 제목 title = div.item-title > a
titles = soup.select('div.item-title > strong.tit-g.clamp-g > a')
itmes_find_list = [] 
for i, title in enumerate(titles):
    itmes_find_list.append({'no': i, 
                            'title' : title.text,
                            'link' : title.attrs['href']})

import pandas as pd    
pd.DataFrame(itmes_find_list)

,no,title,link
0,0,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
3,3,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
4,4,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
5,5,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
6,6,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
7,7,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
8,8,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
9,9,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020

In [220]:
# 방법 1-2. 2차원 리스트
import requests
from bs4 import BeautifulSoup
keyword = '비트코인'
url = "https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q="+keyword+'p='+page_n
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
itmes_find_list = [] # 검색할 결과를 담을 2차원 리스트
titles = soup.select('div.item-title > strong.tit-g.clamp-g > a')
for i, title in enumerate(titles):
    itmes_find_list.append([i, title.text, title.attrs['href']])

import pandas as pd    
pd.DataFrame(itmes_find_list, columns=['no', 'title', 'link'])

,no,title,link
0,0,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
1,1,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
2,2,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
3,3,"블랙록, 자사 비트코인 ETF 보유량 25% 확대…기관 투자 본격화 신호탄",http://v.daum.net/v/20250528151802080
4,4,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
5,5,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
6,6,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
7,7,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
8,8,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
9,9,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020

In [224]:
# 페이지를 이동하며 크롤링
# 다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd   
import time
keyword = '비트코인'
page = 1
# url = f"https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q={keyword}&p={page}"
url = f"https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8" # 필요없을 것 같은거 지워버림
params = {'q':keyword, 'p':page}   # 파라미터가 많은 경우에 이와 같이 처리함
response = requests.get(url, params=params)
soup = BeautifulSoup(response.text, 'html.parser')
itmes_find_list = [] # 검색할 결과를 담을 2차원 리스트
titles = soup.select('div.item-title > strong.tit-g.clamp-g > a')
for i, title in enumerate(titles):
    itmes_find_list.append([(page-1)*10 + i, title.text, title.attrs['href']])

import pandas as pd    
pd.DataFrame(itmes_find_list, columns=['no', 'title', 'link'])

# 아래에 함수로 간편하게 선언하자

,no,title,link
0,0,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
1,1,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
2,2,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
3,3,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
4,4,"블랙록, 자사 비트코인 ETF 보유량 25% 확대…기관 투자 본격화 신호탄",http://v.daum.net/v/20250528151802080
5,5,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
6,6,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
7,7,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
8,8,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
9,9,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761

In [241]:
# 함수 다음 뉴스 검색(키워드, 원하는 페이지수)
import requests
from bs4 import BeautifulSoup
import pandas as pd   
import time

def daum_news_crawling(keyword, page=1):
    '''
    다음 뉴스탭에서 키워드로 다음 검색한 결과를 return
    '''    
    url = f"https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8"
    params = {'q':keyword, 'p':page} 
    response = requests.get(url, params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    itmes_find_list = [] # 검색할 결과를 담을 2차원 리스트
    titles = soup.select('div.item-title > strong.tit-g.clamp-g > a')
    for i, title in enumerate(titles):
        itmes_find_list.append({'no': (page-1)*10 + i, 
                            'title' : title.text,
                            'link' : title.attrs['href']})
    return itmes_find_list

In [243]:
result = []
keyword = '비트코인'
pages = 3
for page in range(1,pages+1):
    result.extend( daum_news_crawling(keyword, page) )
    time.sleep(1)  # 1초씩 시간을 두고 수행
# len(result), result

result_df = pd.DataFrame(result)
result_df

,no,title,link
0,0,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
1,1,"블랙록, 자사 비트코인 ETF 보유량 25% 확대…기관 투자 본격화 신호탄",http://v.daum.net/v/20250528151802080
2,2,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
3,3,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
4,4,“맥O날드보다 맛없어!” 혹평이 가득한 트럼프 만찬과 비트코인 피자데이[엠블록레터],http://v.daum.net/v/20250528143002735
5,5,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
6,6,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
7,7,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
8,8,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020
9,9,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
10,10,"달러 스테이블코인, 국내 거래 확산…당국 외환흐름 통제력 약화 우려",http://v.daum.net/v/20250528152520516
11,11,"전력거래소, `공감·혁신` 토대 조직문화 바꾸기",http://v.daum.net/v/20250528152647580
12,12,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258
13,13,[포토]라스베이거스에서 열린 2025 비트코인 콘퍼런스,http://v.daum.net/v/20250528155536962
14,14,연일 최고가 경신하는 비트코인…투자자들 강 건너 불구경하는 이유는,http://v.daum.net/v/20250526212400275
15,15,"""비트코인 산다""…트럼프家, 25억달러 자금 조달 추진[코인브리핑]",http://v.daum.net/v/20250528111837527
16,16,[김대호 박사의 오늘의 키워드] 소비자신뢰지수·비트코인 2025·머스크 한마디·애...,http://v.daum.net/v/20250528071325361
17,17,"비트코인과 엇갈리는 이더리움·리플, 왜?",http://v.daum.net/v/20250526164319028
18,18,잘 나가는 비트코인 산다는데 왜?…트럼프 미디어 주가 10% 급락 [투자360],http://v.daum.net/v/20250528074002668
19,19,"“미국 대통령이 이래도 되나”…트럼프 일가, 4조원 유치해 대놓고 코인 투자",http://v.daum.net/v/20250527220300328
20,20,"<단독>""예배 참석하면 코인 드려요. 5년 안에 비트코인 넘어섭니다""..신앙심 노...",http://v.daum.net/v/20250528083323774
21,21,"트럼프미디어, 비트코인 3.4조 투자 발표에 주가 10% 폭락",http://v.daum.net/v/20250528080206055
22,22,“가상화폐=애완용 돌” 직격했던 ‘월가황제’ 돌변…美 1위 은행도 주목한 ‘이것’...,http://v.daum.net/v/20250528153835219
23,23,"비트레이어, 비트코인 채굴업체와 협력...“BTC 디파이로 나아갈 것”",http://v.daum.net/v/20250527114126672
24,24,뉴욕증시 휴장에 10.9만弗선 숨고른 비트코인 [매일코인],http://v.daum.net/v/20250527103810840
25,25,"스트래티지, 비트코인 4020개 추가 매입...보유량 58만개 돌파",http://v.daum.net/v/20250527081116129
26,26,"""죽고 싶지 않으면 비트코인 비번 내놔""···외국인 납치·고문한 '가상자산 왕'",http://v.daum.net/v/20250528060036428
27,27,"[영상] “강세장 진입한 비트코인, 내년 2분기까지 최소 20만~30만 달러 갈 듯”",http://v.daum.net/v/20250527090137566
28,28,"美 트럼프 대통령, EU 관세 연기…비트코인, 1.67% 상승",http://v.daum.net/v/20250527072542319
29,29,"""비트코인, 해킹에 안전한 시간 20년 남아…완벽한 양자컴에 뚫려""",http://v.daum.net/v/20250527084812094

In [246]:
keywords = ['청바지', '면바지']
pages = 5
result0 = [] # 청바지 검색결과 50개
result1 = [] # 면바지 검색결과 50개
for i, keyword in enumerate(keywords):
    for page in range(1, pages+1):
        print(f'~ ~ ~ {i} 번째 {keyword} {page}p 검색중입니다 ~ ~ ~')
        if i==0:
            result0.extend( daum_news_crawling(keyword, page) )
        else:
            result1.extend( daum_news_crawling(keyword, page) )
        time.sleep(3)
else:
    print('------작업이 완료되었습니다------')

~ ~ ~ 0 번째 청바지 1p 검색중입니다 ~ ~ ~
~ ~ ~ 0 번째 청바지 2p 검색중입니다 ~ ~ ~
~ ~ ~ 0 번째 청바지 3p 검색중입니다 ~ ~ ~
~ ~ ~ 0 번째 청바지 4p 검색중입니다 ~ ~ ~
~ ~ ~ 0 번째 청바지 5p 검색중입니다 ~ ~ ~
~ ~ ~ 1 번째 면바지 1p 검색중입니다 ~ ~ ~
~ ~ ~ 1 번째 면바지 2p 검색중입니다 ~ ~ ~
~ ~ ~ 1 번째 면바지 3p 검색중입니다 ~ ~ ~
~ ~ ~ 1 번째 면바지 4p 검색중입니다 ~ ~ ~
~ ~ ~ 1 번째 면바지 5p 검색중입니다 ~ ~ ~
------작업이 완료되었습니다------

In [247]:
result0_df = pd.DataFrame(result0)
result1_df = pd.DataFrame(result1)
display(result0_df,result1_df)

,no,title,link
0,0,"'이병헌♥' 이민정, 매장 통째로 빌려 청바지 쇼핑",http://v.daum.net/v/20250528050507783
1,1,"“추앙받을 만 하네”… 김지원, 셔츠에 청바지만 입어도 공항 ‘정지’",http://v.daum.net/v/20250526182411395
2,2,흰 티셔츠에 청바지 정석대로 입는 법,http://v.daum.net/v/20250527185425864
3,3,"이민정, 매장 빌려 폭풍 쇼핑 ""10년 전 샀던 청바지는 응급실""(MJ)",http://v.daum.net/v/20250527191015309
4,4,"‘이병헌♥’ 이민정, 청바지 사는데 매장 통째로 빌렸다..남다른 쇼핑 클래스 “나...",http://v.daum.net/v/20250527192310643
5,5,이시영처럼 다리 길어보이고 싶어서 청바지 분석함 [입스타그램],http://v.daum.net/v/20250519172231644
6,6,"'의사 그만둔' 고윤정, 흰 티+청바지...""정석 미녀"" [★해시태그]",http://v.daum.net/v/20250522182007490
7,7,"""청렴이 최고"" … 창원특례시 성산구 문화위생과, '청바지 데이' 추진",http://v.daum.net/v/20250511091428626
8,8,"패셔니스타 김지원, 청바지가 어울리는 여자랍니다! [포토]",http://v.daum.net/v/20250518220139191
9,9,"박병은 ""류준하로 3개월 활동""…청바지 모델 시절 언급",http://v.daum.net/v/20250519190323957
10,10,"60대인데요, 청바지를 다시 입었습니다",http://v.daum.net/v/20250430145405823
11,11,"'45kg' 윤은혜, 청바지가 헐렁…'40세' 비현실적 자기관리 끝판왕",http://v.daum.net/v/20250513174826265
12,12,"173㎝ 장원영 맵시 美쳤네, 청바지 하나 입었을 뿐인데 [스타화보]",http://v.daum.net/v/20250522115656470
13,13,"손담비, 출산 한 달도 안 됐는데 외출…청바지 폼 애엄마 맞나",http://v.daum.net/v/20250506171902866
14,14,"48세 김희선, 흰 셔츠+청바지 기본템 입었을 뿐인데‥미모 레전드",http://v.daum.net/v/20250511134648392
15,15,"윤은혜, 40세 맞아?…청바지도 헐렁한 극세사 몸매+동안 미모",http://v.daum.net/v/20250515063005066
16,16,“브래지어에 청바지만”…20년만에 속옷 모델 된 추성훈 아내 야노 시호 ‘파격’,http://v.daum.net/v/20250515195400237
17,17,‘청바지’ 입은 안철수 ‘학식’ 이준석 쫓아갔지만,http://v.daum.net/v/20250521160401791
18,18,"길은혜,'청바지 핏 뽐내며 입장' [사진]",http://v.daum.net/v/20250523182738772
19,19,"손담비, 출산 한달만 살 쏙 빼고 청바지까지 성공! 41세 출산 안 믿기네",http://v.daum.net/v/20250507150816172
20,20,[리빙포인트] 무릎 튀어나온 청바지엔 소주,http://v.daum.net/v/20250521002847303
21,21,"손담비, 출산한지 한 달도 안 됐는데…완벽 청바지 핏에 '감탄'",http://v.daum.net/v/20250506162501650
22,22,"네포 베이비, 소피아 리치 그레인지가 청바지를 입는 방법",http://v.daum.net/v/20250509182459873
23,23,"수영, ♥정경호가 13년째 반한 청바지핏‥시구 여신 된 ‘소시’ 대표 각선미",http://v.daum.net/v/20250512104326967
24,24,"서현, '4000m' 알프스 만년설 배경으로 '찰칵'…후드티+청바지로도 빛나는 미모",http://v.daum.net/v/20250519055004613
25,25,"서예지, 청바지에 티셔츠만 입어도 남달라 '편안하면서도 고급스러운 공항패션'",http://v.daum.net/v/20250507173140715
26,26,"""이염 걱정 끝""…청바지도 알아서 찬물 세탁, 삼성 세탁건조기 승부수",http://v.daum.net/v/20250522133141787
27,27,기본 청바지 하나로 핀터레스트 출근 룩 완성하는 법,http://v.daum.net/v/20250429110538414
28,28,"근로자의 날, 청바지에 담긴 노동자의 꿈… EBS 다큐 '메이드 인 방글라데시'",http://v.daum.net/v/20250429001004063
29,29,"""청바지가 잘 어울리는 여자"" 채시라였나.. 노영심과 '갤러리 재회'",http://v.daum.net/v/20250422013007276
30,30,아이브 가을 ‘청바지핏 뽐내는 시구’ [MK포토],http://v.daum.net/v/20250527184503588
31,31,"'윤남기♥' 이다은, 다이어트 21kg 감량 효과 있네···완벽한 청바지 자태",http://v.daum.net/v/20250427195408997
32,32,"손담비, 출산 25일 만에 외출…붓기 없이 청바지 ‘완벽핏’ [MD★스타]",http://v.daum.net/v/20250506155104793
33,33,"하이키 옐, ‘톡식’ 커버 영상 화제…흰 티+청바지로도 ‘핫해’",http://v.daum.net/v/20250430145626938
34,34,"효민, 신행 다녀와서 ♥S대 금융맨家 찾았나? 흰티+청바지 청순룩 컴백",http://v.daum.net/v/20250430135410662
35,35,청바지에 운동화 차림의 이재명 후보,http://v.daum.net/v/20250504174727603
36,36,“추앙받을만” 김지원…니트·청바지로 ‘출국장 술렁’,http://v.daum.net/v/20250519072916151
37,37,"레드벨벳 아이린, 아담한 키에도 완벽 청바지핏‥여전한 청순美",http://v.daum.net/v/20250508143509849
38,38,"결혼 앞둔 서동주, 흰 티+청바지로 볼륨 몸매 자랑 [DA★]",http://v.daum.net/v/20250426094238780
39,39,"결혼 앞둔 서동주, 청바지만 입어도 놀라운 볼륨 몸매 [N샷]",http://v.daum.net/v/20250501091858958
40,40,"'6월 결혼' 서동주, 흰 티에 청바지로도 눈에 띄는 '몸매 천재'",http://v.daum.net/v/20250427233923159
41,41,"김지원 '셔츠에 청바지, 드레스도 아닌데 이렇게 우아해'",http://v.daum.net/v/20250526183900812
42,42,청바지 입고 험지 집중공략…이재명 “내가 뭘 잘못했나”,http://v.daum.net/v/20250505005118075
43,43,청바지 한 벌에 담긴 ‘의류 노동자들의 꿈’,http://v.daum.net/v/20250428210858958
44,44,"‘나는 반딧불’ 황가람, ‘청바지 콘서트’ 초고속 전석 매진",http://v.daum.net/v/20250412164209352
45,45,"“청바지로 바닥 청소?” 제니→기은세, 땅에 끌리는 청바지가 올 봄 대세 [스타와치]",http://v.daum.net/v/20250323141858594
46,46,"‘이병헌♥’ 이민정, 둘째 출산 후 깨달은 핸드크림의 소중함…쇼핑은 여전히 ‘즉흥...",http://v.daum.net/v/20250528083601842
47,47,주말 나들이 룩 고민을 단번에 끝내줄 청바지 한 장,http://v.daum.net/v/20250411121526610
48,48,[T포토] 아이들 슈화 '특이한 청바지',http://v.daum.net/v/20250519165630503
49,49,"서동주, 결혼 앞두고 미모 폭발 ‘흰티+청바지는 진리’ [★SNS]",http://v.daum.net/v/20250427141331451

,no,title,link
0,0,사천에서 쾌청한 날씨 속 탁 트인 남해 풍경 즐겨요!,http://v.daum.net/v/20250528104429529
1,1,"윤승아, ♥김무열 쏙 빼닮은 깜찍 子 하객룩 공개‥벌써 우월한 유전자",http://v.daum.net/v/20250526145941690
2,2,"이번 주 포천 여행,반팔 하나로 충분할까?",http://v.daum.net/v/20250527171732518
3,3,"이재명, 첫 대학 방문…이준석 겨냥?",http://v.daum.net/v/20250526191942751
4,4,"""나는 젊어"" 팔소매 접은 이준석의 '흰셔츠' 속에도 뼈가 담겼다[21대 대선 리...",http://v.daum.net/v/20250525070013619
5,5,이재명 ‘간담회’ 이준석 ‘학식’…20대 표심 공략 [21대 대선],http://v.daum.net/v/20250526171503637
6,6,"대학생 만난 이재명 ""청년 극소수가 극우화…근묵자흑처럼 오염""",http://v.daum.net/v/20250526141950437
7,7,'배우자 토론' 자신감 얻은 김문수…딸·사위까지 총출동,http://v.daum.net/v/20250522185207535
8,8,정동원 첫사랑 품은 순정남 변신 ‘꽃등’ 라이브 클립 공개,http://v.daum.net/v/20250519123006455
9,9,"장년 품격을 높이는 '피어스 브로스넌'의 패션 꿀팁 3종 세트[長靑年, 늘 푸른 ...",http://v.daum.net/v/20250514043027212
10,10,"이재명, 편안한 이미지… 김문수, TPO 저격… 이준석, 젊음 부각[6·3 대선후...",http://v.daum.net/v/20250514050142756
11,11,"독해진 김문수 ""난 방탄조끼 안 입어…총 맞을 일 있으면 맞겠다""",http://v.daum.net/v/20250520175109269
12,12,김 “난 방탄입법 필요없다”,http://v.daum.net/v/20250521004241451
13,13,[오늘의 운세] 2025년 5월 22일 별자리 운세,http://v.daum.net/v/20250522060214587
14,14,이재명·김문수·이준석 색다른 '3가지 맛'… 대선후보 '말말말',http://v.daum.net/v/20250515103236747
15,15,이재명의 적은 이재명 이미지? 'YS 성대모사' 유세까지 한다[대선 인사이드],http://v.daum.net/v/20250513050130424
16,16,"[최준호의 사이언스&] 용각산에서 시작한 제약기업 보령, 우주사업 나선 이유",http://v.daum.net/v/20250513001821091
17,17,안전운행 순한 맛 … 액셀밟는 매운 맛 … 모두까기 쏘는 맛,http://v.daum.net/v/20250513180908084
18,18,"금강제화, 정장·면바지 모두 어울리는 '리갈 U팁 경량드레스 구두'…캐주얼 슈즈 ...",http://v.daum.net/v/20250312161111159
19,19,"[스타트 브리핑] 李 ""나도 계엄"" 金 ""개가 짖냐"" 조작 영상... 대선 앞 퍼...",http://v.daum.net/v/20250514065813695
20,20,"순한맛 이재명, 매운맛 김문수, 쏘는맛 이준석…3색 스타일 대결",http://v.daum.net/v/20250513193015643
21,21,2025년 이재명 후보가 ‘파랑+빨강’ 운동화 신은 이유,http://v.daum.net/v/20250513142008244
22,22,[김교석의 남자의 물건] [13] 휴 그랜트처럼… 셔츠가 그려내는 남자의 멋,http://v.daum.net/v/20250509001947194
23,23,[오늘의 운세] 2025년 5월 11일 별자리 운세,http://v.daum.net/v/20250511060216848
24,24,"황동주, 이영자와 썸타더니 패션도 화제‥연하 남친룩의 정석",http://v.daum.net/v/20250501155743263
25,25,한센인마을 찾은 김문수 “행정이 할 일은 단속 아니라 보살핌”,http://v.daum.net/v/20250505005440109
26,26,"'파기환송' 후 골목 누빈 이재명...""어떡해요"" 묻는 시민에 한 말",http://v.daum.net/v/20250501221200845
27,27,"황동주, 7살 연상 ♥이영자 공개열애 후 패션도 달라졌다..연하 남친룩",http://v.daum.net/v/20250501120929636
28,28,"한센촌 찾아 눈물보인 김문수 ""행정의 본질은 낮은 곳 향한 돌봄""",http://v.daum.net/v/20250504170703863
29,29,"황동주, 7세 연상 ♥이영자 만나더니..'연하 남친룩' 그 자체",http://v.daum.net/v/20250501130030409
30,30,"황동주, 미중년의 정석",http://v.daum.net/v/20250501233616918
31,31,"""숨어 살던 제게 손 내밀어줬다"" 한센인 편지에…김문수 울컥",http://v.daum.net/v/20250504175034661
32,32,"황동주, 꾸안꾸→댄디美 ‘섹시 꽃중년’",http://v.daum.net/v/20250501120702562
33,33,"판교서 만난 '앙숙' 안철수·이준석…""더 일찍 만났어야"" [종합]",http://v.daum.net/v/20250425172907812
34,34,"엑소 카이, 트와이스 모모와 로버x셋미프리 잇는 2년만의 챌린지",http://v.daum.net/v/20250426194654737
35,35,"'이과' 대선후보 '앙숙' 안철수·이준석…""이렇게 생각 비슷했나""",http://v.daum.net/v/20250425155738212
36,36,"성시경, 김밥 솜씨 후덜덜.. ""국수는 언제 먹여줄건가요""",http://v.daum.net/v/20250425043006532
37,37,"60대인데요, 청바지를 다시 입었습니다",http://v.daum.net/v/20250430145405823
38,38,'면바지' 치노팬츠 다시 찾는다,http://v.daum.net/v/20241012093012938
39,39,[오늘의 운세] 2025년 04월 27일 별자리 운세,http://v.daum.net/v/20250427000302021
40,40,"차주영, 주먹만한 얼굴에 눈이 반‥비현실적 인형 미모 ‘깜짝’",http://v.daum.net/v/20250406150159294
41,41,"김원중♥곽지영, 혼전순결→예쁜 딸 얻어도 신혼 같아‥세상 힙한 부부",http://v.daum.net/v/20250327104347111
42,42,"'케빈오♥' 공효진, 염치없어도 사랑하니까…무릎 위 7kg 얹기",http://v.daum.net/v/20250320221605936
43,43,[세상보기] 엄마와 면바지,http://v.daum.net/v/20220221070815649
44,44,시크하면서 스타일리시… 발끝에 ‘한 끗 차이’를 더하다,http://v.daum.net/v/20250321003114746
45,45,"[현장포토] ""가려도 멋짐""…이민호, 로맨틱 출국길",http://v.daum.net/v/20250319151800282
46,46,"[현장포토] ""멋짐을 입었어""…이민호, 완벽한 비주얼",http://v.daum.net/v/20250319152101415
47,47,[더오래]올 여름 쿠바 카라 셔츠에 면바지로 뽐내 보시죠,http://v.daum.net/v/20200812150043353
48,48,[오늘의 운세] 2025년 03월 23일 별자리 운세,http://v.daum.net/v/20250323000304785
49,49,"구재이 ""남편 코디 내가 직접, 면바지 로망""",http://v.daum.net/v/20210628235719061

In [252]:
result0_df.to_csv('data/ch14_'+keywords[0]+'.csv', index=False, encoding='cp949')
result1_df.to_csv('data/ch14_'+keywords[1]+'.csv', index=False)

### 4) user-agent를 추가하여 크롤링
- urlopen() 함수를 사용하면 크롤링이 안되는 사이트
- user-agent를 추가하여 크롤링

In [258]:
# 방법2
from urllib.request import urlopen, Request
# response = urlopen(url)  # url 오픈에서는 한글이 url에 들어가있으면 에러가 난다
keyword = '비트코인'
url = "https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q="+keyword
import urllib.parse

keyword = urllib.parse.quote(keyword) # '비트코인' => '%EB%B9%84%ED%8A%B8%EC%BD%94%EC%9D%B8'
url = "https://search.daum.net/search?w=news&nil_search=btn&DA=NTB&enc=utf8&cluster=y&cluster_page=1&q="+keyword
headers = {'user-agent' : \
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers = headers)
response = urlopen(request)
soup = BeautifulSoup(response, 'html.parser')
soup
titles = soup.select('div.item-title > strong.tit-g.clamp-g > a')
itmes_find_list = [] 
for i, title in enumerate(titles):
    itmes_find_list.append({'no': i, 
                            'title' : title.text,
                            'link' : title.attrs['href']})

import pandas as pd    
pd.DataFrame(itmes_find_list)
# 결과물 없음. 불러올수가 없기 때문에. 브라우저가 접속을 한 것으로 우회를 할 필요가 있음.

,no,title,link
0,0,美·日 국채 팔고 비트코인 샀다…'안전자산' 등극,http://v.daum.net/v/20250528154126316
1,1,[비트코인 2025] 백악관 크립토 차르 “美 정부 비트코인 추가 매입 검토…부채...,http://v.daum.net/v/20250528103907230
2,2,[비즈 나우] 비트코인 2025 컨퍼런스 개막…'전략자산' 선언 코앞,http://v.daum.net/v/20250528075215864
3,3,"블랙록, 자사 비트코인 ETF 보유량 25% 확대…기관 투자 본격화 신호탄",http://v.daum.net/v/20250528151802080
4,4,"비트코인, 트럼프 미디어 비축 소식에도 주춤…1억5100만원대",http://v.daum.net/v/20250528095112897
5,5,"美 상원의원 ""트럼프 대통령, 비트코인법 지지""",http://v.daum.net/v/20250528090342853
6,6,[비트코인 2025] 로빈후드 창업자 “토큰화 증권은 美 ‘자본 패권’ 키우는 수단”,http://v.daum.net/v/20250528110600761
7,7,"트럼프미디어그룹, 25억 달러 규모 자금 조달 통해 비트코인 매입 예고",http://v.daum.net/v/20250528084245020
8,8,"'비트코인 빚투' 스트레티지, 또 샀다…보유량 58만개 돌파",http://v.daum.net/v/20250528042404292
9,9,"숨 고르는 비트코인, 10만8000달러선 '주춤'",http://v.daum.net/v/20250528095921258

### n) yes24 베스트셀러 크롤링 연습

In [127]:
# 방법1
import requests
response = requests.get('https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=24')
soup = BeautifulSoup(response.content, 
                    "html.parser")
gd_names = soup.select('a.gd_name')
for i, gd_name  in enumerate(gd_names):
        print(f'{i+1}. {gd_name.text}')

1. 청춘의 독서
2. 엄마의 말 연습
3. 어른의 품격을 채우는 100일 필사 노트
4. 단 한 번의 삶
5. 이로운 보수 의로운 진보
6. 소년이 온다
7. 어른의 행복은 조용하다
8. 초역 부처의 말
9. 모순
10. 빛과 실
11. 쇼펜하우어 인생수업 : 한 번뿐인 삶 이렇게 살아라 (리커버 에디션)
12. 듀얼 브레인
13. 괴수 8호 15 트리플특장판
14. 길고양이와 늑대 5 더블특전판
15. 혼모노
16. 위버멘쉬
17. 결국 국민이 합니다
18. 급류
19. 에그박사 15
20. 첫 여름, 완주
21. 친구가 상처 줄 때 똑똑하게 나를 지키는 법
22. 친구 사이에도 예의가 필요해
23. 서랍에 저녁을 넣어 두었다
24. 워런 버핏 웨이

### 5) 멜론 차트 크롤링
- 꼭 user-agent를 사용해야 하는 경우 
- https://www.melon.com/chart/index.htm

In [264]:
# 방법 1
import requests
from bs4 import BeautifulSoup
url = "https://www.melon.com/chart/"
melon_chart = requests.get(url)
melon_chart  # 406 코드는 막혀있다는 뜻. 1번 방법은 할 수 없다

In [278]:
# 방법 2
from urllib.request import urlopen, Request
url = "https://www.melon.com/chart/"
headers = {'user-agent' :
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'}
request = Request(url, headers=headers)
melon_chart = urlopen(request)

#방법 1
melon_chart = requests.get(url, headers=headers)
soup = BeautifulSoup(melon_chart.text, 'html.parser')
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="4022717807957185" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/9d/x/e9gkymzs.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/l8/i/bmqlrmeyi7uljr5.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<link href="https://static.melon.co.kr/static/web/resource/style/w1/dn/4/ynesuqe51i.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://static.melon.co.kr/static/web/resource/style/w1/qa/5/rlbqwv6hljdyw.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20250528" type="text/javascript"></script>
<script src="https://static.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="clfix">
<li class="first_child d_melon_ticket"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="//ticket.melon.com/main/index.htm" title="멜론 티켓"><span>멜론 티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="clfix">
<li class="first_child"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="menu02 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="/event/vip/index.htm" title="멜론라운지"><span>멜론라운지</span></a></li>
<li><a class="menu03 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/list.htm" title="이벤트"><span>이벤트</span></a></li>
<li class="last_child"><a class="menu04 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;
								var gradeImageUrl = gradeInfo.HTTPSIMAGEURL;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}

								try {

									gradeImageUrl = gradeImageUrl.replace('http:','');

									if(gradeName == '일반'){
										gradeImageUrl = "";
									}

									if(gradeImageUrl != ''){
										gradeImg = "<span class=\"icon_logon\"><img src=\""+gradeImageUrl+"\" width=\"18\" height=\"18\" alt=\""+gradeName+"\" /></span>";
									}
									//카카오연동확인
									if(memberType == '1'){
										gradeImg += '<span class="icon_logon"><img src="//cdnimg.melon.co.kr/resource/image/web/common/icon_kakao.png" width="18" height="18" alt="kakao"></span>';
									}
								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');"><img src="//cdnimg.melon.co.kr/resource/image/web/common/btn_top_logout.png" width="44" height="12" alt="로그아웃"></button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong></a> 님</span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<!-- 140603_수정 -->
<h1><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="MelOn 로고 - 홈으로 이동"><img alt="Melon" height="99" src="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" width="142"/></a></h1>
<!-- //140603_수정 -->
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" style="width:249px" title="검색 입력 편집창" type="text"/><input id="keywordLink" name="keywordLink" type="hidden" value=""/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none">급상승 키워드</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden; height:20px;">
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner"></div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/hot100/index.htm"><span class="menu_chart m6">HOT100</span></a></li><!-- // MELONUIT-2465 -->
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>
<li class=""><a href="//www.melon.com/new/album/index.htm"><span class="menu_new m2">최신앨범</span></a></li>
<li class=""><a href="//www.melon.com/new/mv/index.htm"><span class="menu_new m3">최신 뮤직비디오</span></a></li>
</ul>
</div>
</li>
<li class="nth3">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C03&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu03">장르 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="menu_gnr nm1">한국대중음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0900"><span class="menu_gnr nm2">해외POP음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN1500"><span class="menu_gnr nm3">그외 인기장르</span></a></li>
</ul>
</div>
</li>
<li class="nth4">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S04&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/dj/today/djtoday_list.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu04">멜론DJ</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/dj/today/djtoday_list.htm"><span class="menu_dj m1">오늘은 뭘 듣지</span></a></li>
<li class=""><a href="//www.melon.com/dj/essential/djessential_list.htm"><span class="menu_dj m2">전문가 선곡</span></a></li>
<li class=""><a href="//www.melon.com/dj/themegenre/djthemegenre_list.htm"><span class="menu_dj m3">#테마장르</span></a></li>
<li class=""><a href="//www.melon.com/dj/powerdj/djpowerdj_list.htm"><span class="menu_dj m4">파워DJ</span></a></li>
<li class=""><a href="//www.melon.com/dj/chart/djchart_list.htm"><span class="menu_dj m5">인기</span></a></li>
</ul>
</div>
</li>
<li class="nth5">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S05&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/tv/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu05">멜론TV</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/tv/index.htm"><span class="menu_tv m1">오늘은 뭘 볼까</span></a></li>
<li class=""><a href="//www.melon.com/tv/mv/index.htm"><span class="menu_tv m2">뮤직비디오</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=1"><span class="menu_tv m3">멜론 오리지널</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=4"><span class="menu_tv m4">아티스트 업데이트</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=3"><span class="menu_tv m5">방송</span></a></li>
</ul>
</div>
</li>
<li class="nth6">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S07&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu06">스타포스트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="menu_arti m1">NOW</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/artistchart/index.htm"><span class="menu_arti m3">아티스트 랭킹</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/myranking/index.htm"><span class="menu_arti m4">마이 랭킹</span></a></li>
</ul>
<div class="menu_artist_btn">
<div class="artist_fan">
<button class="btn_fan" onclick="MELON.WEBSVC.POC.menu.goMyMusicFanSignArtist();" type="button"><span class="odd_span">팬맺은 아티스트</span></button>
</div>
<div class="artist_finder">

In [304]:
# 멜론 순위, 곡명, 가수명, 좋아요수
# 1위 | 너에게 닿기를 | 10CM | ♥ 85,756
# 곡명 = div.wrap_song_info > div.ellipsis.rank01
# 가수명 = div.wrap_song_info > div.ellipsis.rank02 > span
# 좋아요수 = div.wrap > button > span.cnt
titles = soup.select('div.wrap_song_info > div.ellipsis.rank01')
title = [t.text.strip() for t in titles]
# len(title), title
artists = soup.select('div.wrap_song_info > div.ellipsis.rank02 > span')
artist = [a.text for a in artists]
chart = []
for i, (t, a) in enumerate(zip(title, artist)):
    chart.append({'Rank' : str(i+1)+'위', 
                  'Title': t, 
                  'Artist' : a})

chart_df = pd.DataFrame(chart)
chart_df

    Rank                         Title        Artist
0     1위                       너에게 닿기를          10CM
1     2위            Never Ending Story           아이유
2     3위                      Drowning         WOODZ
3     4위                   like JENNIE   제니 (JENNIE)
4     5위              모르시나요(PROD.로코베리)           조째즈
..   ...                           ...           ...
95   96위                        Sticky  KISS OF LIFE
96   97위  Small girl (feat. 도경수(D.O.))           이영지
97   98위                          Dash         PLAVE
98   99위                   사막에서 꽃을 피우듯    우디 (Woody)
99  100위                   다시 만날 수 있을까           임영웅

[100 rows x 3 columns]